# Generated by Django 4.2.1 on 2023-05-13 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_remove_room_follower_room_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
