# Generated by Django 4.2.1 on 2023-05-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_message_alter_room_follower_delete_post_message_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
